using Entity;

namespace Service;
class SehirService 
{
    public List<Sehir> sehirler = new List<Sehir>
    {
        new Sehir(1, "Adana"),
        new Sehir(2, "Adıyaman"),
        new Sehir(3, "Afyonkarahisar"),
        new Sehir(4, "Ağrı"),
        new Sehir(5, "Amasya"),
        new Sehir(6, "Ankara"),
        new Sehir(7, "Antalya"),
        new Sehir(8, "Artvin"),
        new Sehir(9, "Aydın"),
        new Sehir(10, "Balıkesir"),
        new Sehir(11, "Bilecik"),
        new Sehir(12, "Bingöl"),
        new Sehir(13, "Bitlis"),
        new Sehir(14, "Bolu"),
        new Sehir(15, "Burdur"),
        new Sehir(16, "Bursa"),
        new Sehir(17, "Çanakkale"),
        new Sehir(18, "Çankırı"),
        new Sehir(19, "Çorum"),
        new Sehir(20, "Denizli"),
        new Sehir(21, "Diyarbakır"),
        new Sehir(22, "Edirne"),
        new Sehir(23, "Elazığ"),
        new Sehir(24, "Erzincan"),
        new Sehir(25, "Erzurum"),
        new Sehir(26, "Eskişehir"),
        new Sehir(27, "Gaziantep"),
        new Sehir(28, "Giresun"),
        new Sehir(29, "Gümüşhane"),
        new Sehir(30, "Hakkari"),
        new Sehir(31, "Hatay"),
        new Sehir(32, "Isparta"),
        new Sehir(33, "Mersin"),
        new Sehir(34, "İstanbul"),
        new Sehir(35, "İzmir"),
        new Sehir(36, "Kars"),
        new Sehir(37, "Kastamonu"),
        new Sehir(38, "Kayseri"),
        new Sehir(39, "Kırklareli"),
        new Sehir(40, "Kırşehir"),
        new Sehir(41, "Kocaeli"),
        new Sehir(42, "Konya"),
        new Sehir(43, "Kütahya"),
        new Sehir(44, "Malatya"),
        new Sehir(45, "Manisa"),
        new Sehir(46, "Kahramanmaraş"),
        new Sehir(47, "Mardin"),
        new Sehir(48, "Muğla"),
        new Sehir(49, "Muş"),
        new Sehir(50, "Nevşehir"),
        new Sehir(51, "Niğde"),
        new Sehir(52, "Ordu"),
        new Sehir(53, "Rize"),
        new Sehir(54, "Sakarya"),
        new Sehir(55, "Samsun"),
        new Sehir(56, "Siirt"),
        new Sehir(57, "Sinop"),
        new Sehir(58, "Sivas"),
        new Sehir(59, "Tekirdağ"),
        new Sehir(60, "Tokat"),
        new Sehir(61, "Trabzon"),
        new Sehir(62, "Tunceli"),
        new Sehir(63, "Şanlıurfa"),
        new Sehir(64, "Uşak"),
        new Sehir(65, "Van"),
        new Sehir(66, "Yozgat"),
        new Sehir(67, "Zonguldak"),
        new Sehir(68, "Aksaray"),
        new Sehir(69, "Bayburt"),
        new Sehir(70, "Karaman"),
        new Sehir(71, "Kırıkkale"),
        new Sehir(72, "Batman"),
        new Sehir(73, "Şırnak"),
        new Sehir(74, "Bartın"),
        new Sehir(75, "Ardahan"),
        new Sehir(76, "Iğdır"),
        new Sehir(77, "Yalova"),
        new Sehir(78, "Karabük"),
        new Sehir(79, "Kilis"),
        new Sehir(80, "Osmaniye"),
        new Sehir(81, "Düzce")
    };
}